import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import type { DrillType } from '@lib/bluelock-taxonomy';

export interface AthletePreferences {
  preferredFocuses: DrillType[];
  sessionStyle: 'balanced' | 'aggressive' | 'recovery';
  availableMinutes: number;
  prefersOutdoor: boolean;
  autoGenerateDailyRoutine: boolean;
}

export interface AthleteLocationSnapshot {
  latitude: number;
  longitude: number;
  label: string | null;
  updatedAt: string;
}

export interface AthleteWeatherSnapshot {
  temp: number;
  condition: 'Rain' | 'Clear' | 'Clouds' | 'Wind' | 'Fog' | 'Unknown';
  description: string;
  locationLabel: string;
  fetchedAt: string;
}

export interface DailyBriefing {
  date: string;
  headline: string;
  subheadline: string;
  createdAt: string;
}

export interface BlueLockNotification {
  id: string;
  type: 'daily_quote' | 'training_plan' | 'training_nudge' | 'motivation';
  title: string;
  body: string;
  createdAt: string;
  deliveredAt?: string | null;
  readAt?: string | null;
}

interface AthleteProfileState {
  ownerUid: string | null;
  preferences: AthletePreferences;
  location: AthleteLocationSnapshot | null;
  weather: AthleteWeatherSnapshot | null;
  dailyBriefing: DailyBriefing | null;
  notifications: BlueLockNotification[];
  lastDailyRoutineDate: string | null;
  bindOwner: (uid: string | null) => void;
  hydrateFromCloud: (
    payload: Partial<
      Pick<
        AthleteProfileState,
        'preferences' | 'location' | 'weather' | 'dailyBriefing' | 'notifications' | 'lastDailyRoutineDate'
      >
    >,
    uid: string
  ) => void;
  setPreferences: (preferences: Partial<AthletePreferences>) => void;
  setLocation: (location: AthleteLocationSnapshot) => void;
  setWeather: (weather: AthleteWeatherSnapshot) => void;
  setDailyBriefing: (briefing: DailyBriefing) => void;
  upsertNotification: (notification: BlueLockNotification) => void;
  markNotificationRead: (id: string) => void;
  markNotificationDelivered: (id: string) => void;
  setLastDailyRoutineDate: (date: string | null) => void;
  resetAthleteProfile: () => void;
}

const DEFAULT_PREFERENCES: AthletePreferences = {
  preferredFocuses: ['velocidade', 'drible', 'chute'],
  sessionStyle: 'balanced',
  availableMinutes: 20,
  prefersOutdoor: true,
  autoGenerateDailyRoutine: true,
};

function cloneDefaultPreferences() {
  return {
    ...DEFAULT_PREFERENCES,
    preferredFocuses: [...DEFAULT_PREFERENCES.preferredFocuses],
  };
}

export const useAthleteProfileStore = create<AthleteProfileState>()(
  persist(
    (set) => ({
      ownerUid: null,
      preferences: cloneDefaultPreferences(),
      location: null,
      weather: null,
      dailyBriefing: null,
      notifications: [],
      lastDailyRoutineDate: null,

      bindOwner: (uid) => {
        set((state) => {
          if (state.ownerUid === uid) {
            return state;
          }

          return {
            ownerUid: uid,
            preferences: cloneDefaultPreferences(),
            location: null,
            weather: null,
            dailyBriefing: null,
            notifications: [],
            lastDailyRoutineDate: null,
          };
        });
      },

      hydrateFromCloud: (payload, uid) => {
        set({
          ownerUid: uid,
          preferences: {
            ...cloneDefaultPreferences(),
            ...(payload.preferences ?? {}),
            preferredFocuses: payload.preferences?.preferredFocuses?.length
              ? payload.preferences.preferredFocuses
              : cloneDefaultPreferences().preferredFocuses,
          },
          location: payload.location ?? null,
          weather: payload.weather ?? null,
          dailyBriefing: payload.dailyBriefing ?? null,
          notifications: payload.notifications ?? [],
          lastDailyRoutineDate: payload.lastDailyRoutineDate ?? null,
        });
      },

      setPreferences: (preferences) => {
        set((state) => ({
          preferences: {
            ...state.preferences,
            ...preferences,
            preferredFocuses: preferences.preferredFocuses?.length
              ? preferences.preferredFocuses
              : state.preferences.preferredFocuses,
          },
        }));
      },

      setLocation: (location) => {
        set({ location });
      },

      setWeather: (weather) => {
        set({ weather });
      },

      setDailyBriefing: (dailyBriefing) => {
        set({ dailyBriefing });
      },

      upsertNotification: (notification) => {
        set((state) => {
          const currentIndex = state.notifications.findIndex((candidate) => candidate.id === notification.id);
          const nextNotifications = [...state.notifications];

          if (currentIndex >= 0) {
            nextNotifications[currentIndex] = {
              ...nextNotifications[currentIndex],
              ...notification,
            };
          } else {
            nextNotifications.unshift(notification);
          }

          return {
            notifications: nextNotifications.slice(0, 24),
          };
        });
      },

      markNotificationRead: (id) => {
        set((state) => ({
          notifications: state.notifications.map((notification) =>
            notification.id === id
              ? {
                  ...notification,
                  readAt: notification.readAt ?? new Date().toISOString(),
                }
              : notification
          ),
        }));
      },

      markNotificationDelivered: (id) => {
        set((state) => ({
          notifications: state.notifications.map((notification) =>
            notification.id === id
              ? {
                  ...notification,
                  deliveredAt: notification.deliveredAt ?? new Date().toISOString(),
                }
              : notification
          ),
        }));
      },

      setLastDailyRoutineDate: (lastDailyRoutineDate) => {
        set({ lastDailyRoutineDate });
      },

      resetAthleteProfile: () => {
        set({
          ownerUid: null,
          preferences: cloneDefaultPreferences(),
          location: null,
          weather: null,
          dailyBriefing: null,
          notifications: [],
          lastDailyRoutineDate: null,
        });
      },
    }),
    {
      name: 'bluelock-athlete-profile-v1',
    }
  )
);
