'use client';

import { useEffect, useEffectEvent } from 'react';
import { flattenWikiEntries } from '@lib/bluelock-content';
import { materializeSkillTreeEntries, materializeTrainingPlan, materializeWikiEntries } from '@lib/anri/apply';
import {
  buildDailyBriefing,
  calculateTrainingStreak,
  createDailyQuoteNotification,
  createMotivationNotification,
  createTrainingNudgeNotification,
  createTrainingPlanNotification,
  fetchWeatherForLocation,
  formatLocalDateKey,
  resolveBrowserLocation,
} from '@lib/athlete-daily';
import { useAthleteProfileStore } from '@store/useAthleteProfileStore';
import { useBlueLockContentStore } from '@store/useBlueLockContentStore';
import { useEgoStore } from '@store/useEgoStore';
import { useAuth } from '@lib/AuthContext';

function isOlderThan(isoDate: string | null | undefined, minutes: number) {
  if (!isoDate) return true;
  return Date.now() - new Date(isoDate).getTime() > minutes * 60_000;
}

export default function AthleteAutomation() {
  const { user, profile } = useAuth();
  const xp = useEgoStore((state) => state.xp);
  const rank = useEgoStore((state) => state.rank);
  const skills = useEgoStore((state) => state.skills);
  const history = useEgoStore((state) => state.history);
  const upsertSkills = useEgoStore((state) => state.upsertSkills);

  const wikiEntries = useBlueLockContentStore((state) => state.wikiEntries);
  const trainingPlan = useBlueLockContentStore((state) => state.trainingPlan);
  const pendingTrainingPlan = useBlueLockContentStore((state) => state.pendingTrainingPlan);
  const trainingPresets = useBlueLockContentStore((state) => state.trainingPresets);
  const addWikiEntries = useBlueLockContentStore((state) => state.addWikiEntries);
  const suggestTrainingPlan = useBlueLockContentStore((state) => state.suggestTrainingPlan);
  const saveTrainingPreset = useBlueLockContentStore((state) => state.saveTrainingPreset);

  const preferences = useAthleteProfileStore((state) => state.preferences);
  const location = useAthleteProfileStore((state) => state.location);
  const weather = useAthleteProfileStore((state) => state.weather);
  const dailyBriefing = useAthleteProfileStore((state) => state.dailyBriefing);
  const notifications = useAthleteProfileStore((state) => state.notifications);
  const lastDailyRoutineDate = useAthleteProfileStore((state) => state.lastDailyRoutineDate);
  const setLocation = useAthleteProfileStore((state) => state.setLocation);
  const setWeather = useAthleteProfileStore((state) => state.setWeather);
  const setDailyBriefing = useAthleteProfileStore((state) => state.setDailyBriefing);
  const upsertNotification = useAthleteProfileStore((state) => state.upsertNotification);
  const markNotificationDelivered = useAthleteProfileStore((state) => state.markNotificationDelivered);
  const setLastDailyRoutineDate = useAthleteProfileStore((state) => state.setLastDailyRoutineDate);

  const ensureDailyRoutine = useEffectEvent(async () => {
    if (!user || profile?.role !== 'trainee' || !preferences.autoGenerateDailyRoutine) {
      return;
    }

    const todayKey = formatLocalDateKey();
    if (lastDailyRoutineDate === todayKey) {
      return;
    }

    try {
      const idToken = await user.getIdToken();
      const response = await fetch('/api/anri', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${idToken}`,
        },
        body: JSON.stringify({
          channel: 'daily_automation',
          messages: [
            {
              sender: 'user',
              text: 'Monte a rotina diária de hoje para o Bernardo. Priorize um treino curto, objetivo e adaptado ao clima atual e ao histórico recente. Evite criar técnicas novas se o repertório atual já resolver.',
            },
          ],
          athlete: {
            xp,
            rank,
            unlockedSkills: skills
              .filter((skill) => skill.unlocked)
              .map((skill) => ({
                id: skill.id,
                name: skill.name,
                type: skill.type,
                tier: skill.tier,
                requiredXp: skill.requiredXp,
                unlocked: skill.unlocked,
                dependencyNames: skill.dependencies
                  .map((dependencyId) => skills.find((candidate) => candidate.id === dependencyId)?.name)
                  .filter((dependencyName): dependencyName is string => Boolean(dependencyName)),
              })),
            lockedSkillCount: skills.filter((skill) => !skill.unlocked).length,
            recentHistory: history.slice(0, 5).map((entry) => ({
              type: entry.type,
              xpEarned: entry.xpEarned,
              date: entry.date,
            })),
          },
          wikiEntries: flattenWikiEntries(wikiEntries),
          currentTraining: trainingPlan.drills,
          currentTrainingPlan: trainingPlan,
          skillTree: skills.map((skill) => ({
            id: skill.id,
            name: skill.name,
            type: skill.type,
            tier: skill.tier,
            requiredXp: skill.requiredXp,
            description: skill.description,
            createdBy: skill.createdBy,
            linkedWikiEntryTitle: skill.linkedWikiEntryTitle,
            unlocked: skill.unlocked,
            dependencyIds: skill.dependencies,
            dependencyNames: skill.dependencies
              .map((dependencyId) => skills.find((candidate) => candidate.id === dependencyId)?.name)
              .filter((dependencyName): dependencyName is string => Boolean(dependencyName)),
          })),
          environment: weather
            ? {
                weatherCondition: weather.condition,
                weatherDescription: weather.description,
                temperatureC: weather.temp,
                locationLabel: weather.locationLabel,
              }
            : {
                weatherCondition: 'Unknown',
                weatherDescription: 'clima ainda não lido, usar prudência',
                temperatureC: null,
                locationLabel: location?.label || 'Última localização salva',
              },
          preferences,
          trainingPresets: trainingPresets.map((preset) => ({
            id: preset.id,
            name: preset.name,
            focus: preset.plan.focus,
            rationale: preset.plan.rationale,
            savedAt: preset.savedAt,
          })),
        }),
      });

      const payload = await response.json();
      if (!response.ok) {
        throw new Error(payload?.error || 'Falha ao gerar rotina diária.');
      }

      if (payload.wikiEntries?.length) {
        addWikiEntries(materializeWikiEntries(payload.wikiEntries));
      }

      if (payload.skillTreeEntries?.length) {
        upsertSkills(materializeSkillTreeEntries(payload.skillTreeEntries, skills));
      }

      if (payload.trainingPlan) {
        const nextPlan = materializeTrainingPlan(payload.trainingPlan, trainingPlan.drills);

        suggestTrainingPlan(nextPlan, {
          suggestedBy: 'daily_routine',
          presetName: payload.trainingDirective?.presetName ?? null,
        });

        if (payload.trainingDirective?.action === 'save_preset' || payload.trainingDirective?.action === 'save_preset_and_confirm_swap') {
          saveTrainingPreset(payload.trainingDirective.presetName || payload.trainingPlan.title, {
            ...nextPlan,
            source: 'anri',
            updatedAt: new Date().toISOString(),
          }, 'anri');
        }

        upsertNotification(createTrainingPlanNotification(todayKey, payload.trainingPlan.title));
      }

      setLastDailyRoutineDate(todayKey);
    } catch (error) {
      console.warn('Nao foi possivel gerar a rotina diaria da Anri.', error);
    }
  });

  useEffect(() => {
    if (!user || profile?.role !== 'trainee') return;
    if (!location || isOlderThan(location.updatedAt, 360)) {
      void resolveBrowserLocation()
        .then(setLocation)
        .catch((error) => {
          console.warn('Nao foi possivel atualizar a geolocalizacao do atleta.', error);
        });
    }
  }, [user, profile?.role, location, setLocation]);

  useEffect(() => {
    if (!location) return;
    if (!weather || isOlderThan(weather.fetchedAt, 90)) {
      void fetchWeatherForLocation(location)
        .then(setWeather)
        .catch((error) => {
          console.warn('Nao foi possivel atualizar o clima local.', error);
        });
    }
  }, [location, weather, setWeather]);

  useEffect(() => {
    if (!user || profile?.role !== 'trainee') return;

    const todayKey = formatLocalDateKey();
    if (dailyBriefing?.date !== todayKey) {
      const nextBriefing = buildDailyBriefing({
        history,
        rank,
      });
      setDailyBriefing(nextBriefing);
      upsertNotification(createDailyQuoteNotification(nextBriefing));
    }
  }, [user, profile?.role, dailyBriefing, history, rank, setDailyBriefing, upsertNotification]);

  useEffect(() => {
    if (!user || profile?.role !== 'trainee') return;
    void ensureDailyRoutine();
  }, [user, profile?.role, weather, location, ensureDailyRoutine]);

  useEffect(() => {
    if (!user || profile?.role !== 'trainee') return;

    const todayKey = formatLocalDateKey();
    const now = new Date();
    const streak = calculateTrainingStreak(history);
    const trainedToday = history.some((entry) => formatLocalDateKey(new Date(entry.date)) === todayKey);
    const availablePlanTitle = pendingTrainingPlan?.title || trainingPlan.title;

    if (now.getHours() >= 13 && availablePlanTitle) {
      upsertNotification(createTrainingPlanNotification(todayKey, availablePlanTitle));
    }

    if (now.getHours() >= 18 && !trainedToday) {
      upsertNotification(createTrainingNudgeNotification(todayKey, streak));
    }

    if (now.getHours() >= 9) {
      upsertNotification(createMotivationNotification(todayKey, rank));
    }
  }, [user, profile?.role, history, pendingTrainingPlan?.title, trainingPlan.title, rank, upsertNotification]);

  useEffect(() => {
    if (typeof window === 'undefined' || !('Notification' in window) || Notification.permission !== 'granted') {
      return;
    }

    for (const notification of notifications) {
      if (notification.deliveredAt) continue;

      new Notification(notification.title, {
        body: notification.body,
        tag: notification.id,
      });
      markNotificationDelivered(notification.id);
    }
  }, [notifications, markNotificationDelivered]);

  return null;
}
